### ISSUE TITLE
Rebranding a cloned repo without giving proper credit! COOL ❌

### ISSUE THREAD

**Issue by sitch** [elixir-waffle/waffle#38]
You guys should probably mention some rationale as to why this is effectively a complete fork and rebrand (why?) of the `arc` project.. 

It's honestly pretty gross to see a page like this: https://evrone.com/waffle-elixir-library where your team gives the illusion of coming out with some great new project when all you did was fork a prominent but no longer regularly maintained project..

The least you could do is reference the arc project and explain that its no longer maintained.  I did see a small reference in the licensing.. but i don't know about you all..

Demerits to you guys.. :-1: :-1:

**Comment by achempion** [comment]
Hi Sitch,

Thank you for rising this issue and describing your concerns.

Just in case couple of citations from the link you provided
> Waffle grew out of a fork of a now-unsupported library, to which we've added complete documentation, fixed outstanding issues, merged open pull requests

> This release of Waffle is v1.0.0. If you've previously used Arc, you'll find the transition to Waffle very straightforward

About rebranding... I wanted to use Arc name at first but unfortunately I can't do it because of Apache License. Arc namespace occupied in package manager as well by the original project.

If you have other concerns I'll be happy to address them.

**Comment by achempion** [comment]
I've updated the README to address future possible misunderstandings of the library origins.

**Comment by sitch** [comment]
I think it would also give credibility to ask the arc maintainers to put a deprecated warning and link to repo as i don't think there's been a commit on there in ~2yrs
