### ISSUE TITLE
*Question/Request* Digitalocean Spaces Support?

### ISSUE THREAD

**Issue by firrae** [elixir-waffle/waffle#62]
### Environment

* Elixir version (elixir -v): 1.10.4
* Waffle version (mix deps): haven't installed yet
* Waffle dependencies when applicable (mix deps): haven't installed yet
* Operating system: Linux (Manjaro 18)

### Expected behavior
I am looking to upload to [Digitalocean Spaces](https://www.digitalocean.com/products/spaces/) as my object storage/CDN but I'm curious how to do this with Waffle. It is S3 API compatible, so is it as simple as using the S3 config and swapping S3 URL for Spaces URLs?

I haven't had a chance to try it yet, but if someone knows already then it'd be great to start running faster from peoples existing knowledge.

**Comment by firrae** [comment]
Specifically the part that I think I need to change to maybe "just make it work" is here: https://hexdocs.pm/waffle/Waffle.Storage.S3.html#module-alternate-s3-configuration-example

**Comment by achempion** [comment]
Hi Steve,

Here is my configuration in `releases.exs` but for Linode instead of DO.

- S3_BUCKET=achempion-com
- S3_ASSET_HOST=https://achempion-com.us-east-1.linodeobjects.com/
- S3_HOST=us-east-1.linodeobjects.com
- s3_key=...
- s3_secret=...

config :ex_aws,
  json_codec: Jason,
  access_key_id: s3_key,
  secret_access_key: s3_secret,
  s3: [
   host: System.get_env("S3_HOST")
  ]

config :waffle,
  storage: Waffle.Storage.S3,
  bucket: System.get_env("S3_BUCKET"),
  asset_host: System.get_env("S3_ASSET_HOST")

I think DO storage should be similar. You can publish an example for DO
and I'll add it to the documentation.

**Comment by hectorsq** [comment]
This is my config for Digital Ocean

```elixir
config :waffle,
  storage: Waffle.Storage.S3,
  bucket: "my_bucket"

config :ex_aws,
  debug_requests: true,
  json_codec: Jason,
  access_key_id: "my_access_key_id",
  secret_access_key: "my_secret_access_key"

config :ex_aws, :s3,
  scheme: "https://",
  host: "sfo2.digitaloceanspaces.com",
  region: "sfo2"
```

**Comment by firrae** [comment]
I had something very similar to @hectorsq, and what I didn't have I'm taking and it seems to work as well ;p
